# Generated by Django 2.1 on 2020-09-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='decription',
            new_name='description',
        ),
    ]
